# -*- coding: utf-8 -*-
"""ML Model for recognizing numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cgzn7alBnsO001Um-oM_2BNH_JZnlNrW
"""

from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
import numpy as np

# Load the dataset
digits = load_digits()

# What does the dataset look like?
print("Feature matrix shape:", digits.data.shape)
print("Labels shape:", digits.target.shape)
print("Classes:", digits.target_names)

fig, axes = plt.subplots(2, 5, figsize=(10, 5))

for i, ax in enumerate(axes.flat):
    ax.imshow(digits.images[i], cmap='gray_r')
    ax.set_title(f"Label: {digits.target[i]}")
    ax.axis('off')

plt.suptitle("Sample digits from the dataset", y=1.02)
plt.tight_layout()
plt.show()

unique, counts = np.unique(digits.target, return_counts=True)
for digit, count in zip(unique, counts):
    print(f"Digit {digit}: {count} samples")

from sklearn.model_selection import train_test_split

X = digits.data
y = digits.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training samples:", X_train.shape[0])
print("Test samples:", X_test.shape[0])

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000, random_state=42)
model.fit(X_train_scaled, y_train)

print("Training complete!")
print("Classes learned:", model.classes_)

from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test_scaled)

print("Test accuracy:", accuracy_score(y_test, y_pred))

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix

cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=model.classes_)

fig, ax = plt.subplots(figsize=(10, 10))
disp.plot(ax=ax, cmap='Blues')
plt.title("Confusion Matrix")
plt.show()

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

fig, axes = plt.subplots(2, 5, figsize=(12, 5))

for i, ax in enumerate(axes.flat):
    # Each row of coef_ is the 64 weights for one digit
    coef_image = model.coef_[i].reshape(8, 8)
    ax.imshow(coef_image, cmap='RdBu', interpolation='nearest')
    ax.set_title(f"Digit: {i}")
    ax.axis('off')

plt.suptitle("What the model learned per digit", y=1.02)
plt.tight_layout()
plt.show()

fig, axes = plt.subplots(2, 5, figsize=(12, 5))

for i, ax in enumerate(axes.flat):
    coef_image = model.coef_[i].reshape(8, 8)
    ax.imshow(coef_image, cmap='RdBu', interpolation='nearest',
              vmin=-0.5, vmax=0.5)  # tighten the color range
    ax.set_title(f"Digit: {i}")
    ax.axis('off')

plt.suptitle("What the model learned per digit", y=1.02)
plt.tight_layout()
plt.show()

import tensorflow as tf
print(tf.__version__)

import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

# Load data
digits = load_digits()
X = digits.data
y = digits.target

# Reshape from (1797, 64) to (1797, 8, 8, 1)
# CNN expects: (samples, height, width, channels)
X = X.reshape(-1, 8, 8, 1)

# Normalize pixel values to 0-1
X = X / 16.0

# One-hot encode labels
y = to_categorical(y, num_classes=10)

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

model = Sequential([
    # First convolutional block
    Conv2D(32, kernel_size=(3, 3), activation='relu', padding='same', input_shape=(8, 8, 1)),
    MaxPooling2D(pool_size=(2, 2)),

    # Second convolutional block
    Conv2D(64, kernel_size=(3, 3), activation='relu', padding='same'),

    # Flatten and classify
    Flatten(),
    Dense(64, activation='relu'),
    Dropout(0.5),
    Dense(10, activation='softmax')
])

model.summary()

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    X_train, y_train,
    epochs=30,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)

import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report
import numpy as np

# Get predictions
y_pred_probs = model.predict(X_test)
y_pred = np.argmax(y_pred_probs, axis=1)
y_true = np.argmax(y_test, axis=1)

# Accuracy
from sklearn.metrics import accuracy_score
print("Test accuracy:", accuracy_score(y_true, y_pred))

# Confusion matrix
cm = confusion_matrix(y_true, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=range(10))
fig, ax = plt.subplots(figsize=(10, 10))
disp.plot(ax=ax, cmap='Blues')
plt.title("CNN Confusion Matrix")
plt.show()

# Classification report
print(classification_report(y_true, y_pred))

plt.figure(figsize=(12, 4))

# Accuracy plot
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Training accuracy')
plt.plot(history.history['val_accuracy'], label='Validation accuracy')
plt.title('Accuracy over epochs')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

# Loss plot
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Training loss')
plt.plot(history.history['val_loss'], label='Validation loss')
plt.title('Loss over epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

