# -*- coding: utf-8 -*-
"""ML Model for recognizing numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cgzn7alBnsO001Um-oM_2BNH_JZnlNrW
"""

from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
import numpy as np

# Load the dataset
digits = load_digits()

# What does the dataset look like?
print("Feature matrix shape:", digits.data.shape)
print("Labels shape:", digits.target.shape)
print("Classes:", digits.target_names)

fig, axes = plt.subplots(2, 5, figsize=(10, 5))

for i, ax in enumerate(axes.flat):
    ax.imshow(digits.images[i], cmap='gray_r')
    ax.set_title(f"Label: {digits.target[i]}")
    ax.axis('off')

plt.suptitle("Sample digits from the dataset", y=1.02)
plt.tight_layout()
plt.show()

unique, counts = np.unique(digits.target, return_counts=True)
for digit, count in zip(unique, counts):
    print(f"Digit {digit}: {count} samples")

from sklearn.model_selection import train_test_split

X = digits.data
y = digits.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training samples:", X_train.shape[0])
print("Test samples:", X_test.shape[0])

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000, random_state=42)
model.fit(X_train_scaled, y_train)

print("Training complete!")
print("Classes learned:", model.classes_)

from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test_scaled)

print("Test accuracy:", accuracy_score(y_test, y_pred))

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix

cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=model.classes_)

fig, ax = plt.subplots(figsize=(10, 10))
disp.plot(ax=ax, cmap='Blues')
plt.title("Confusion Matrix")
plt.show()

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

fig, axes = plt.subplots(2, 5, figsize=(12, 5))

for i, ax in enumerate(axes.flat):
    # Each row of coef_ is the 64 weights for one digit
    coef_image = model.coef_[i].reshape(8, 8)
    ax.imshow(coef_image, cmap='RdBu', interpolation='nearest')
    ax.set_title(f"Digit: {i}")
    ax.axis('off')

plt.suptitle("What the model learned per digit", y=1.02)
plt.tight_layout()
plt.show()

fig, axes = plt.subplots(2, 5, figsize=(12, 5))

for i, ax in enumerate(axes.flat):
    coef_image = model.coef_[i].reshape(8, 8)
    ax.imshow(coef_image, cmap='RdBu', interpolation='nearest',
              vmin=-0.5, vmax=0.5)  # tighten the color range
    ax.set_title(f"Digit: {i}")
    ax.axis('off')

plt.suptitle("What the model learned per digit", y=1.02)
plt.tight_layout()
plt.show()

